// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX_AnVP0I1_ikS_Brm89Yawdv3g6n-6Vg',
    appId: '1:929641300990:web:213b4c2befff9232e3f6af',
    messagingSenderId: '929641300990',
    projectId: 'blancaflor-advmblprog',
    authDomain: 'blancaflor-advmblprog.firebaseapp.com',
    storageBucket: 'blancaflor-advmblprog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm1UkzLyqPLaWJRxw9wc1nkAYzOw1Gebk',
    appId: '1:929641300990:android:95f9e4740aef3cf5e3f6af',
    messagingSenderId: '929641300990',
    projectId: 'blancaflor-advmblprog',
    storageBucket: 'blancaflor-advmblprog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHIrT5rOERa4ZKXEvWG_JJFwLa_sCRd0g',
    appId: '1:929641300990:ios:b4882b4ceb04ebbde3f6af',
    messagingSenderId: '929641300990',
    projectId: 'blancaflor-advmblprog',
    storageBucket: 'blancaflor-advmblprog.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHIrT5rOERa4ZKXEvWG_JJFwLa_sCRd0g',
    appId: '1:929641300990:ios:b4882b4ceb04ebbde3f6af',
    messagingSenderId: '929641300990',
    projectId: 'blancaflor-advmblprog',
    storageBucket: 'blancaflor-advmblprog.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX_AnVP0I1_ikS_Brm89Yawdv3g6n-6Vg',
    appId: '1:929641300990:web:e9ad75d1ee5e020de3f6af',
    messagingSenderId: '929641300990',
    projectId: 'blancaflor-advmblprog',
    authDomain: 'blancaflor-advmblprog.firebaseapp.com',
    storageBucket: 'blancaflor-advmblprog.firebasestorage.app',
  );
}
